WIP feature/update clang format and tidy
Zuehlke/cpp_example_project pull request #13
Opened 2022-05-05 20:03 UTC by StephanKa

- reformat all files using new clang-format rules

2022-05-24 15:18 UTC, arnemertz requested changes

2022-05-24 15:18 UTC, arnemertz commented on .clang-tidy
> +WarningsAsErrors: ''
baut das nicht die warnings as errors aus, d.h. Warnings sind keine Errors mehr?

2022-05-24 15:18 UTC, arnemertz commented on CMakeLists.txt
> +CMAKE_MINIMUM_REQUIRED(VERSION 3.15)
warum alles auf Caps? die ganzen anderen CMake files im Projekt benutzen doch auch lowecase?

2022-05-30 11:38 UTC, StephanKa commented on .clang-tidy
> +WarningsAsErrors: ''
alle anderen CMakeFiles sind auch formatiert worden damit es einheitlich ist

2022-05-30 11:38 UTC, StephanKa commented on CMakeLists.txt
> +CMAKE_MINIMUM_REQUIRED(VERSION 3.15)
alle anderen CMakeFiles sind auch formatiert worden damit es einheitlich ist

2022-05-30 19:52 UTC, StephanKa commented on .clang-tidy
> +WarningsAsErrors: ''
entfernt

2022-05-31 04:27 UTC, arnemertz approved these changes

2022-05-31 04:54 UTC, merged